image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable 
packages:
   - nixpkgs.hut
   - nixpkgs.hugo
   - nixpkgs.tailwindcss
   - nixpkgs.gnumake
environment:
  site: prma.dev
tasks:
    - publish: |
        cd prmadev
        make publish
