image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
triggers: 
  - action: email
    condition: failure
    to: logins@prma.dev
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable 
packages:
   - nixpkgs.hut
   - nixpkgs.hugo
   - nixpkgs.tailwindcss
   - nixpkgs.gnumake
   - nixpkgs.lychee
   - nixpkgs.fd
environment:
  site: prma.dev
tasks:
    - publish: |
        cd prmadev
        make publish
