image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable 
packages:
   - nixpkgs.hut
   - nixpkgs.hugo
   - nixpkgs.tailwindcss
   - nixpkgs.gnumake
   - nixpkgs.lychee
   - nixpkgs.fd
environment:
  site: prma.dev
tasks:
    - check-links: |
        cd prmadev
        hugo
        lychee $(fd .html public/)
    - publish: |
        cd prmadev
        make publish
