baseURL = 'https://prma.dev/'
languageCode = 'en-us'
title = 'prma'
titleCaseStyle = 'none'
copyright = "CC v.4"
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true
paginate = 3
timeZone = 'Europe/Berlin'
[taxonomies]
tag = "tags"
category = "categories"
audience = "audiences"

[params]
AuthorName = 'Perma'
GitHubUser = 'prmadev'
Subtitle = 'something good'
icon = '/android-chrome-512x512.png'
favicon = '/favicon.ico'
showFullTextinJSONFeed = true
author.email = 'me@prma.dev'
author.name = 'Perma'
author.url = 'https://prma.dev/'
author.avatar= '/images/me.png'
description ='Personal Blog of Perma'  

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'posts'
  pageRef = '/posts'
  weight = 20




[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 0
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'algol_nu'
    tabWidth = 4

[markup.goldmark.renderer]
  unsafe = true

[mediaTypes]
  [mediaTypes.'application/feed+json']
    suffixes = ['json']
[outputFormats]
  [outputFormats.jsonfeed]
    mediaType = 'application/feed+json'
    baseName = 'feed'
    rel= 'alternate'
    isPlainText= true

[outputs]
home = ['HTML', 'RSS', 'jsonfeed']
section = ['HTML', 'RSS', 'jsonfeed']
taxonomy = ['HTML', 'RSS', 'jsonfeed']
term = ['HTML', 'RSS', 'jsonfeed']

